### ISSUE TITLE
Configuration file parameter

### ISSUE THREAD

**Issue by urcadox** [Keruspe/facron#3]
I found myself needing facron for a one-time thing. I don't want to edit my main config file for this.

Adding an optional -c parameter defining an alternative configuration file would be awesome. :-)

**Comment by Keruspe** [comment]
@urcadox I take it I have to do it myself? :)

**Comment by Keruspe** [comment]
3ee351faa5ac5c13538f908e4a76a721c3f9c34e

**Comment by urcadox** [comment]
Woops, completely forgot that one
